# Exported from Render on 2025-03-13T11:22:52Z
services:
- type: web
  name: portfolio-server
  env: php
  repo: https://github.com/R-G2110/portfolio-server
  plan: free
  region: frankfurt
  buildCommand: "composer install --no-dev --optimize-autoloader && php artisan migrate --force"
  startCommand: php artisan serve --host=0.0.0.0 --port=$PORT"
version: "1"
