# Exported from Render on 2025-03-13T11:22:52Z
services:
- type: web
  name: portfolio-server
  runtime: node
  repo: https://github.com/R-G2110/portfolio-server
  plan: free
  region: frankfurt
  buildCommand: composer install
  startCommand: php artisan serve --host=0.0.0.0 --port=10000
version: "1"
